name: service_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  firebase_messaging: ^14.6.5
  #  google_mobile_ads: ^0.13.0
  crypto: ^3.0.3
  simple_animations: ^5.0.2
  #  supercharged: ^2.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.0
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  flutter_login_facebook: ^1.8.0
  transparent_image: ^2.0.1
  #  in_app_purchase: ^1.0.5
  table_calendar: ^3.0.9
  flutter_svg: ^2.0.7
  razorpay_flutter: ^1.3.5
#  razorpay_web: ^1.4.2
  image_picker: ^1.0.1
  country_picker: ^2.0.20
  custom_sliding_segmented_control: ^1.7.5

  flutter_easyloading: ^3.0.5
  flutter_rating_bar: ^4.0.1
  #  swipebuttonflutter: ^1.0.0
  #  geoflutterfire: ^3.0.1
  google_maps_flutter: ^2.3.1
  location: ^5.0.0
  pin_code_text_field: ^1.8.0
  #  flutterwave: ^1.0.3
  #  flutter_credit_card: ^3.0.3
  #  paytm_allinonesdk: ^1.0.3
  flutter_braintree: ^3.0.0
  flutter_spinkit: ^5.2.0
  #  line_icons: ^2.0.1
  #  flutter_slider_drawer: ^2.1.1
  #  timeago: ^3.3.0
  maps_launcher: ^2.2.0
  url_launcher: ^6.1.12
  #  easy_localization: ^3.0.1
  currency_picker: ^2.0.16
  #  connectivity: ^3.0.6
  introduction_screen: ^3.1.11
  get: ^4.6.5
  get_it: ^7.6.0
  #push: ^0.1.3
  overlay_support: ^2.1.0
  local_auth: ^2.1.6
  carousel_slider: ^4.2.1
  google_mobile_ads: ^3.0.0
  flutter_stripe: ^9.3.0
  #  rate_my_app: ^1.1.3
  facebook_audience_network: ^1.0.1
  flutter_fgbg: ^0.3.0
  socket_io_client: ^2.0.2
  sqflite: ^2.2.8+4
  flutter_contacts: ^1.1.7
  aescryptojs: ^1.0.0
  permission_handler: ^10.4.3
  #  flutter_callkit_incoming: ^1.0.2+1
  #  gallery_saver: ^2.3.2
  pull_to_refresh: ^2.0.0
  flutter_drawing_board: ^0.4.4+2
  google_static_maps_controller: ^1.0.0
  cached_network_image: ^3.2.3
  video_player: ^2.7.0
  dots_indicator: ^2.1.2
  detectable_text_field: ^2.1.0
  keyboard_attachable: ^2.1.0
  story_view: ^0.15.0
  chewie: ^1.7.0
  visibility_detector: ^0.3.3
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  flutter_linkify: ^6.0.0
  #  giphy_get: ^3.1.0
  just_audio: ^0.9.34
  audio_service: ^0.18.10
  audio_video_progress_bar: ^1.0.1
  flutter_ringtone_player: ^3.2.0
  #  wakelock: ^0.6.2
  focused_menu: ^1.0.5
  #  pip_view: ^0.9.7
  #  link_preview_generator: ^1.2.0
  any_link_preview: ^3.0.1
  photo_manager: ^2.6.0
  share_plus: ^7.0.2
  google_mlkit_smart_reply: ^0.8.0
  google_mlkit_commons: ^0.5.0
  flutter_sound: ^9.2.13

  #  awesome_notifications: ^0.7.5-dev.3
  camera: ^0.10.5+2
  profanity_filter: ^2.0.0
  #  place_picker: ^0.9.20-nullsafety
  progress_state_button: ^1.0.4
  map_launcher: ^2.5.0+1
  video_thumbnail: ^0.5.3
  flutter_image_compress: ^2.0.4
  flare_flutter: ^3.0.2
  ripple_wave: ^0.1.3
  #  animated_text_kit: ^4.2.2
  file_picker: ^5.3.2
  flutter_downloader: ^1.10.5
  flutter_keyboard_visibility: ^5.4.1
  video_compress: ^3.1.2
  path_provider: ^2.0.15
  oktoast: ^3.3.1
  #  avatar_glow: ^2.0.2
  pinch_zoom: ^1.0.0
  mime_type: ^1.0.0
  device_info_plus: ^9.0.2
  lottie: ^2.5.0
  simple_animation_progress_bar: ^1.6.0
  csslib: 0.17.3
  percent_indicator: ^4.2.3
  url_strategy: ^0.2.0
  open_filex: ^4.3.2
  extended_image: ^8.0.2
  flutter_local_notifications: ^16.0.0-dev.1
  flutter_staggered_grid_view: ^0.6.2
  universal_html: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/common/
    - assets/icons/
    - assets/social/
    - assets/login/
    - assets/lottie/
    - assets/tabs/
    - assets/profile/
    - assets/tutorial/
    - assets/
    - assets/landingPage/
    - resources/langs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
